;;; emacs-everywhere-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from emacs-everywhere.el

(autoload 'emacs-everywhere "emacs-everywhere" "\
Launch the emacs-everywhere frame from emacsclient.

(fn &optional FILE LINE COLUMN)")
(autoload 'emacs-everywhere-initialise "emacs-everywhere" "\
Entry point for the executable.
APP is an `emacs-everywhere-app' struct.")
(add-hook 'server-visit-hook #'emacs-everywhere-initialise)
(register-definition-prefixes "emacs-everywhere" '("emacs-everywhere-"))

;;; End of scraped data

(provide 'emacs-everywhere-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; emacs-everywhere-autoloads.el ends here
